name: age_calculator
description: تطبيق لحساب العمر بدقة وعرض التفاصيل مع دعم الوضع الليلي.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  provider: ^6.1.2
  hijri_date_time: ^1.1.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
